# Generated by Django 6.0.5 on 2026-06-01 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('18-25', '18-25'), ('26-40', '26-40'), ('41-60', '41-60'), ('60+', '60+')], max_length=20)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer-not-to-say', 'Prefer not to say')], max_length=20)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('goal', models.CharField(blank=True, max_length=100, null=True)),
                ('privacy_consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PosturalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joint_angles', models.JSONField(help_text="Dictionary of joint angles (e.g. {'right_knee': 175})")),
                ('deviations', models.JSONField(help_text="Detected postural deviations (e.g. {'forward_head': True})")),
                ('scan_reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='biometrics.biometricprofile')),
            ],
        ),
    ]
