# Generated by Django 4.2.28 on 2026-06-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricprofile',
            name='age_group',
            field=models.CharField(blank=True, choices=[('18-25', '18-25'), ('26-40', '26-40'), ('41-60', '41-60'), ('60+', '60+')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='biometricprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='biometricprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='biometricprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('prefer-not-to-say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='biometricprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='posturalassessment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
