# Generated by Django 4.2.28 on 2026-06-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0002_alter_biometricprofile_age_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posturalassessment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posture_scans/'),
        ),
        migrations.AddField(
            model_name='posturalassessment',
            name='raw_landmarks',
            field=models.JSONField(blank=True, help_text='Raw 33 landmarks coordinates {x, y, z, visibility}', null=True),
        ),
    ]
