# Generated by Django 6.0.5 on 2026-06-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0003_posturalassessment_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='posturalassessment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='posturalassessment',
            name='image',
            field=models.TextField(blank=True, help_text='Base64 Data URL of the image', null=True),
        ),
    ]
