# Generated by Django 6.0.5 on 2026-08-11 09:07

from django.db import migrations, models


def backfill_from_assessments(apps, schema_editor):
    """Preserve the previous derived semantics for users who already onboarded."""
    BiometricProfile = apps.get_model('biometrics', 'BiometricProfile')
    BiometricProfile.objects.filter(assessments__isnull=False).distinct().update(
        onboarding_complete=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0004_alter_biometricprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricprofile',
            name='onboarding_complete',
            field=models.BooleanField(default=False, help_text='Set when the user finishes the onboarding flow. Explicitly recorded rather than inferred from assessments, so users who skip the body scan are not looped back.'),
        ),
        migrations.RunPython(backfill_from_assessments, migrations.RunPython.noop),
    ]
