# Generated by Django 4.2.28 on 2026-06-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='angle_ranges',
            field=models.JSONField(blank=True, default=dict, help_text='Per-age-band MediaPipe knee angle thresholds for rep counting'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='goal_tags',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["weight_loss", "weight_gain", "general"]'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='rep_config',
            field=models.JSONField(blank=True, default=dict, help_text='Per-age-band sets, reps, and rest period in seconds'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='voice_cues',
            field=models.JSONField(blank=True, default=dict, help_text='Per-age-band cue text strings keyed by error type'),
        ),
    ]
