# Generated by Django 4.2.28 on 2026-06-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_exercise_angle_ranges_exercise_goal_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutsession',
            old_name='date',
            new_name='created_at',
        ),
    ]
