# Generated by Django 4.2.28 on 2026-07-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_rename_date_workoutsession_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='Short looping demo video URL (webm/mp4)'),
        ),
    ]
