# Generated by Django 4.2.28 on 2026-07-15 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_exercise_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='video_url',
        ),
    ]
