# Generated by Django 4.2.28 on 2026-08-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_remove_exercise_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='age_groups_allowed',
            field=models.JSONField(blank=True, default=list, help_text='Age bands for which this exercise is appropriate, e.g. ["18-25", "26-40"]'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='high_impact',
            field=models.BooleanField(default=False, help_text='True if exercise has high joint load; penalised for users with BMI > 30'),
        ),
    ]
