# Generated by Django 6.0.5 on 2026-08-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_add_age_groups_allowed_and_high_impact'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='voice_cue_audio',
            field=models.JSONField(blank=True, default=dict, help_text='Per-age-band pre-rendered cue audio URLs keyed by error type'),
        ),
    ]
