# Generated by Django 4.2.28 on 2026-08-13 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_exercise_voice_cue_audio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consultation',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
