# Generated by Django 6.0.5 on 2026-08-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='image_url',
            field=models.TextField(blank=True, default='', help_text='URL or Base64 data of doctor avatar image'),
        ),
    ]
