# Generated by Django 4.2.28 on 2026-08-12 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctorprofile_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='message',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
